---
abstract: 'A tiny module loader'
author:
  - 'Blabos de Blebe <blabos@cpan.org>'
build_requires:
  File::Spec: '3.47'
  Scalar::Util: '1.38'
  Test::Most: '0.34'
  Test::Perl::Critic: '1.02'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MAD-Loader
requires:
  Carp: '1.12'
  Const::Fast: '0.014'
  Moo: '1.004006'
resources:
  bugtracker: https://github.com/blabos/MAD-Loader/issues
  repository: https://github.com/blabos/MAD-Loader
version: 3.001001_001
