---
abstract: 'A tiny module loader'
author:
  - 'Blabos de Blebe, C<< <blabos at cpan.org> >>'
  - 'Blabos de Blebe <blabos@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MAD-Loader
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 1.12
  Const::Fast: 0.013
  Moo: 1.000008
  perl: 5.8.8
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MAD-Loader
  homepage: http://blabos.org
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: git://github.com/blabos/MAD-Loader.git
version: 2.000003
